name: Tests
on: [ push, pull_request ]

jobs:
  tests_on_macOS:
    name: Tests on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
